version: "3"

volumes:
  db-data: {}

services:
  assignment-api:
    container_name: assignment-api
    image: khaledalmana/assignment-api:latest
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - COMPONENT=assignmentapi
    restart: always
    ports:
      - "8080:8080" # try not to change this port

